dist: trusty
os: linux
language: cpp
compiler: g++
sudo: required

services:
        - docker
branches:
        only:
                - master

addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-6
                        - cmake

script:
        - docker build -t back .
after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        - docker tag back $DOCKER_USER/back:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USER/back:$TRAVIS_BUILD_NUMBER
        - docker tag back $DOCKER_USER/back:latest
        - docker push $DOCKER_USER/back:latest


